<a href="https://colab.research.google.com/github/ANNON17-byte/Coding-Neurons-and-Layers/blob/main/coding_neurons_and_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3 - Input Neuron

In [ ]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2  # bias is extra parameter added to weighed sum , which improve model learning and shift activation func

outputs = (inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias)

print(outputs)

2.3


Layer

In [ ]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

weights1 = weights[0]
weights2 = weights[1]
weights3 = weights[2]
biases = [2, 3, 0.5]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [
    inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
    inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
    inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3,
]

print(output)

[4.8, 1.21, 2.385]


Layer Using Loops

In [ ]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

output = []

#neuron_weight is single neuron weight
for neuron_weights, neuron_bias in zip(weights, biases):  #zip combines two list element by element
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias # adding bias
    output.append(neuron_output)

print(output)



[4.8, 1.21, 2.385]


Single Neuron Using Numpy

In [1]:

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

import numpy as np

#converting to array for dot product
input_array = np.array(inputs)
weight_array = np.array(weights)

output = np.dot(input_array, weight_array) + bias

print(output)

4.8


Layers Of Neurons Using Numpy


In [2]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

import numpy as np

inpuut_array = np.array(inputs)
weight_array = np.array(weights)
bias_array = np.array(biases)

output = np.dot(weight_array, inpuut_array) + bias_array

print(output)

[4.8   1.21  2.385]


Layer Of Neurons Case 2 (whenn inp matrix is 3*4 and output matrix is 3*4)

In [5]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

import numpy as np

inpuut_array = np.array(inputs)
weight_array = np.array(weights)
bias_array = np.array(biases)

output = np.dot(inpuut_array, weight_array.T) + bias_array

print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


2 Layers

In [6]:
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

import numpy as np

inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

#first layer dot product

output1 = np.dot(inputs_array, weights_array.T) + biases_array

#second layer dot product

output2 = np.dot(output1, weights2_array.T) + biases2_array

print(output2)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
